/**
 * Copyright 2018 Quest Software and/or its affiliates
 * and other contributors as indicated by the @author tags.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { TableColumnsConfiguration } from '../../../../core/table/models';

export const DATABASES_COLUMNS_CONF: TableColumnsConfiguration = {
  version: 3,
  columns: [
    {
      name: 'dbName',
      metricKey: 'content.db_name',
      queryKey: 'dbName',
      isFixed: true,
      enabled: true,
      enabledMax: true,
      order: 0,
    },
    {
      name: 'alarmsCount',
      queryKey: 'alarms.alarmCounters',
      isFixed: true,
      enabled: false,
      enabledMax: false,
    },
    {
      name: 'databaseKey',
      queryKey: 'databaseKey.key',
      isFixed: true,
      enabled: false,
      enabledMax: false,
    },
    {
      name: 'timeToFull',
      metricKey: 'timetofull',
      queryKey: 'timeToFull',
      enabled: false,
      enabledMax: false,
      order: 0,
      isNumber: true,
      compareBy: true,
      cbOrder: 0,
    },
    {
      name: 'totalSizeMb',
      metricKey: 'totalsize',
      queryKey: 'totalSizeMb',
      enabled: true,
      enabledMax: true,
      order: 1,
      isNumber: true,
      compareBy: true,
      cbOrder: 1,
    },
    {
      name: 'dataUsedMb',
      metricKey: 'datausedmb',
      queryKey: 'dataUsedMb',
      enabled: true,
      enabledMax: true,
      order: 2,
      isNumber: true,
      compareBy: true,
      cbOrder: 2,
    },
    {
      name: 'dataUsedPct',
      metricKey: 'datausedpct',
      queryKey: 'dataUsedPct',
      enabled: true,
      enabledMax: true,
      order: 3,
      isNumber: true,
      compareBy: true,
      cbOrder: 3,
    },
    {
      name: 'logSizeMb',
      metricKey: 'logmb',
      queryKey: 'logSizeMb',
      enabled: true,
      enabledMax: true,
      order: 4,
      isNumber: true,
      compareBy: true,
      cbOrder: 4,
    },
    {
      name: 'logUsedMb',
      metricKey: 'logusedmb',
      queryKey: 'logUsedMb',
      enabled: true,
      enabledMax: true,
      order: 5,
      isNumber: true,
      compareBy: true,
      cbOrder: 5,
    },
    {
      name: 'logUsedPct',
      metricKey: 'logusedpct',
      queryKey: 'logUsedPct',
      enabled: true,
      enabledMax: true,
      order: 6,
      isNumber: true,
      compareBy: true,
      cbOrder: 6,
    },
    {
      name: 'tableCount',
      metricKey: 'tablecnt',
      queryKey: 'tableCount',
      enabled: false,
      enabledMax: true,
      order: 7,
      isNumber: true,
    },
    {
      name: 'resourcePoolName',
      metricKey: 'resource_pool_name',
      queryKey: 'resourcePoolName',
      enabled: false,
      enabledMax: false,
      order: 8,
      isNumber: false,
    },
    {
      name: 'disks',
      metricKey: 'disks',
      queryKey: 'disks',
      enabled: true,
      enabledMax: true,
      order: 9,
      isNumber: false,
    },
    {
      name: 'poolConsumptionPercentage',
      metricKey: 'pool_consumption_percentage',
      queryKey: 'poolConsumptionPercentage',
      enabled: false,
      enabledMax: false,
      order: 10,
      isNumber: true,
    },
    {
      name: 'isAutoShrinkOn',
      metricKey: 'is_auto_shrink_on',
      queryKey: 'isAutoShrinkOn',
      enabled: false,
      enabledMax: false,
      order: 11,
      isNumber: false,
    },
    {
      name: 'isAutoCreateStatsOn',
      metricKey: 'is_auto_create_stats_on',
      queryKey: 'isAutoCreateStatsOn',
      enabled: false,
      enabledMax: false,
      order: 12,
      isNumber: false,
    },
    {
      name: 'isAutoUpdateStatsOn',
      metricKey: 'is_auto_update_stats_on',
      queryKey: 'isAutoUpdateStatsOn',
      enabled: false,
      enabledMax: false,
      order: 13,
      isNumber: false,
    },
    {
      name: 'isAutoUpdateStatsAsyncOn',
      metricKey: 'is_auto_update_stats_async_on',
      queryKey: 'isAutoUpdateStatsAsyncOn',
      enabled: false,
      enabledMax: false,
      order: 14,
      isNumber: false,
    },
    {
      name: 'isReadOnly',
      metricKey: 'is_read_only',
      queryKey: 'isReadOnly',
      enabled: false,
      enabledMax: false,
      order: 15,
      isNumber: false,
    },
    {
      name: 'logReuseWait',
      metricKey: 'log_reuse_wait',
      queryKey: 'logReuseWait',
      enabled: false,
      enabledMax: false,
      order: 16,
      isNumber: true,
    },
    {
      name: 'dataSizeMb',
      metricKey: 'datamb',
      queryKey: 'dataSizeMb',
      enabled: false,
      enabledMax: true,
      order: 17,
      isNumber: true,
      compareBy: true,
      cbOrder: 7,
    },
    {
      name: 'dataFreeMb',
      metricKey: 'datafreemb',
      queryKey: 'dataFreeMb',
      enabled: false,
      enabledMax: true,
      order: 18,
      isNumber: true,
      compareBy: true,
      cbOrder: 8,
    },
    {
      name: 'logFreeMb',
      metricKey: 'logfreemb',
      queryKey: 'logFreeMb',
      enabled: true,
      enabledMax: false,
      order: 19,
      isNumber: true,
      compareBy: true,
      cbOrder: 9,
    },
    {
      name: 'fileGroupCount',
      metricKey: 'filegroupcnt',
      queryKey: 'fileGroupCount',
      enabled: true,
      enabledMax: false,
      order: 20,
      isNumber: true,
    },
    {
      name: 'growthRate',
      metricKey: 'growthrate',
      queryKey: 'growthRate.avg',
      enabled: false,
      enabledMax: false,
      order: 21,
      isNumber: true,
    },
    {
      name: 'xtpEnabled',
      metricKey: 'xtp_enabled',
      queryKey: 'xtpEnabled',
      enabled: false,
      enabledMax: false,
      order: 22,
      isNumber: false,
    },
    {
      name: 'poolAllocated',
      metricKey: 'pool_allocated',
      queryKey: 'poolAllocated',
      enabled: false,
      enabledMax: false,
      order: 23,
      isNumber: true,
    },
    {
      name: 'poolUsed',
      metricKey: 'pool_used',
      queryKey: 'poolUsed',
      enabled: false,
      enabledMax: false,
      order: 24,
      isNumber: true,
    },
  ],
};
